2024-04-09 11:10:39,143 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Configure stats pid to 19444
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Alexia\.config\wandb\settings
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Alexia\diffusion_ts\wandb\settings
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-09 11:10:39,144 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:_log_setup():527] Logging user logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240409_111039-jfcr2ryg\logs\debug.log
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:_log_setup():528] Logging internal logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240409_111039-jfcr2ryg\logs\debug-internal.log
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:init():567] calling init triggers
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-09 11:10:39,145 INFO    MainThread:19444 [wandb_init.py:init():592] re-initializing run, found existing run on stack: 7yghdcgc
2024-04-09 11:10:39,146 INFO    MainThread:19444 [wandb_run.py:_finish():2052] finishing run fyp_a/test_train_2/7yghdcgc
2024-04-09 11:10:39,147 ERROR   MainThread:19444 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-09 11:10:39,147 INFO    MainThread:19444 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_run.py:_restore():2275] restore
2024-04-09 11:10:39,147 INFO    MainThread:19444 [wandb_run.py:_restore():2281] restore done
2024-04-09 11:10:45,031 INFO    MainThread:19444 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-04-09 11:10:45,031 INFO    MainThread:19444 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-04-09 11:10:45,036 INFO    MainThread:19444 [wandb_run.py:_footer_sync_info():3879] logging synced files
2024-04-09 11:10:45,080 INFO    MainThread:19444 [wandb_init.py:init():617] starting backend
2024-04-09 11:10:45,080 INFO    MainThread:19444 [wandb_init.py:init():621] setting up manager
2024-04-09 11:10:45,081 INFO    MainThread:19444 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-09 11:10:45,082 INFO    MainThread:19444 [wandb_init.py:init():629] backend started and connected
2024-04-09 11:10:45,086 INFO    MainThread:19444 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-09 11:10:45,086 INFO    MainThread:19444 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-09 11:10:45,086 INFO    MainThread:19444 [wandb_init.py:init():721] updated telemetry
2024-04-09 11:10:45,234 INFO    MainThread:19444 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-04-09 11:10:46,632 INFO    MainThread:19444 [wandb_run.py:_on_init():2344] communicating current version
2024-04-09 11:10:46,987 INFO    MainThread:19444 [wandb_run.py:_on_init():2353] got version response upgrade_message: "wandb version 0.16.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-04-09 11:10:46,987 INFO    MainThread:19444 [wandb_init.py:init():805] starting run threads in backend
2024-04-09 11:10:47,221 INFO    MainThread:19444 [wandb_run.py:_console_start():2323] atexit reg
2024-04-09 11:10:47,221 INFO    MainThread:19444 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-04-09 11:10:47,222 INFO    MainThread:19444 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-04-09 11:10:47,222 INFO    MainThread:19444 [wandb_run.py:_redirect():2268] Redirects installed.
2024-04-09 11:10:47,222 INFO    MainThread:19444 [wandb_init.py:init():848] run started, returning control to user process
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Configure stats pid to 19444
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Alexia\.config\wandb\settings
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Alexia\diffusion_ts\wandb\settings
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_init.py:_log_setup():527] Logging user logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240409_114144-9vjtek6n\logs\debug.log
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_init.py:_log_setup():528] Logging internal logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240409_114144-9vjtek6n\logs\debug-internal.log
2024-04-09 11:41:44,594 INFO    MainThread:19444 [wandb_init.py:_jupyter_setup():473] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000200F4CB68E0>
2024-04-09 11:41:44,595 INFO    MainThread:19444 [wandb_init.py:init():567] calling init triggers
2024-04-09 11:41:44,595 INFO    MainThread:19444 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-09 11:41:44,595 INFO    MainThread:19444 [wandb_init.py:init():592] re-initializing run, found existing run on stack: jfcr2ryg
2024-04-09 11:41:44,596 INFO    MainThread:19444 [wandb_run.py:_finish():2052] finishing run fyp_a/test_train_2/jfcr2ryg
2024-04-09 11:41:44,596 INFO    MainThread:19444 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-09 11:41:44,596 INFO    MainThread:19444 [wandb_run.py:_restore():2275] restore
2024-04-09 11:41:44,596 INFO    MainThread:19444 [wandb_run.py:_restore():2281] restore done
2024-04-09 11:41:49,235 INFO    MainThread:19444 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-04-09 11:41:49,235 INFO    MainThread:19444 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-04-09 11:41:49,238 INFO    MainThread:19444 [wandb_run.py:_footer_sync_info():3879] logging synced files
