2024-05-08 08:33:59,668 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-05-08 08:33:59,668 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Configure stats pid to 21004
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Alexia\.config\wandb\settings
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Alexia\diffusion_ts\wandb\settings
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_init.py:_log_setup():527] Logging user logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240508_083359-5jw088nf\logs\debug.log
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_init.py:_log_setup():528] Logging internal logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240508_083359-5jw088nf\logs\debug-internal.log
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_init.py:init():567] calling init triggers
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_init.py:init():592] re-initializing run, found existing run on stack: evom2h51
2024-05-08 08:33:59,670 INFO    MainThread:21004 [wandb_run.py:_finish():2052] finishing run fyp_a/test_train_class/evom2h51
2024-05-08 08:33:59,672 ERROR   MainThread:21004 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-05-08 08:33:59,672 INFO    MainThread:21004 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-08 08:33:59,672 INFO    MainThread:21004 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-05-08 08:33:59,672 INFO    MainThread:21004 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-05-08 08:33:59,672 INFO    MainThread:21004 [wandb_run.py:_restore():2275] restore
2024-05-08 08:33:59,672 INFO    MainThread:21004 [wandb_run.py:_restore():2281] restore done
2024-05-08 08:34:04,611 INFO    MainThread:21004 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-05-08 08:34:04,611 INFO    MainThread:21004 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-05-08 08:34:04,616 INFO    MainThread:21004 [wandb_run.py:_footer_sync_info():3879] logging synced files
2024-05-08 08:34:04,657 INFO    MainThread:21004 [wandb_init.py:init():617] starting backend
2024-05-08 08:34:04,657 INFO    MainThread:21004 [wandb_init.py:init():621] setting up manager
2024-05-08 08:34:04,661 INFO    MainThread:21004 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-08 08:34:04,661 INFO    MainThread:21004 [wandb_init.py:init():629] backend started and connected
2024-05-08 08:34:04,667 INFO    MainThread:21004 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-05-08 08:34:04,667 INFO    MainThread:21004 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-08 08:34:04,667 INFO    MainThread:21004 [wandb_init.py:init():721] updated telemetry
2024-05-08 08:34:04,717 INFO    MainThread:21004 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-05-08 08:34:06,234 INFO    MainThread:21004 [wandb_run.py:_on_init():2344] communicating current version
2024-05-08 08:34:06,657 INFO    MainThread:21004 [wandb_run.py:_on_init():2353] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-08 08:34:06,657 INFO    MainThread:21004 [wandb_init.py:init():805] starting run threads in backend
2024-05-08 08:34:06,995 INFO    MainThread:21004 [wandb_run.py:_console_start():2323] atexit reg
2024-05-08 08:34:06,995 INFO    MainThread:21004 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-05-08 08:34:06,995 INFO    MainThread:21004 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-05-08 08:34:06,995 INFO    MainThread:21004 [wandb_run.py:_redirect():2268] Redirects installed.
2024-05-08 08:34:06,996 INFO    MainThread:21004 [wandb_init.py:init():848] run started, returning control to user process
2024-05-08 08:34:06,996 INFO    MainThread:21004 [wandb_run.py:_config_callback():1347] config_cb None None {'epochs': 500, 'batch_size': 64, 'num_batches_per_epoch': 50, 'learning_rate': 0.001, 'weight_decay': 1e-06, 'maximum_learning_rate': 0.01}
