2024-04-23 10:16:31,195 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-23 10:16:31,195 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Configure stats pid to 21000
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Alexia\.config\wandb\settings
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Alexia\diffusion_ts\wandb\settings
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_init.py:_log_setup():527] Logging user logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240423_101631-wnqcwtxt\logs\debug.log
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_init.py:_log_setup():528] Logging internal logs to c:\Users\Alexia\diffusion_ts\wandb\run-20240423_101631-wnqcwtxt\logs\debug-internal.log
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_init.py:init():567] calling init triggers
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-23 10:16:31,196 INFO    MainThread:21000 [wandb_init.py:init():592] re-initializing run, found existing run on stack: c59yzd8n
2024-04-23 10:16:31,198 INFO    MainThread:21000 [wandb_run.py:_finish():2052] finishing run fyp_a/test_train_2/c59yzd8n
2024-04-23 10:16:31,199 ERROR   MainThread:21000 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-23 10:16:31,199 INFO    MainThread:21000 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-23 10:16:31,199 INFO    MainThread:21000 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-04-23 10:16:31,199 INFO    MainThread:21000 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-23 10:16:31,199 INFO    MainThread:21000 [wandb_run.py:_restore():2275] restore
2024-04-23 10:16:31,199 INFO    MainThread:21000 [wandb_run.py:_restore():2281] restore done
